import {
  Client,
  Lead,
  Call,
  Requirement,
  Quote,
  Project,
  Task,
  TeamMember,
  ProjectMember,
  Payment,
  Maintenance,
  HostingRecord,
  DomainRecord,
  Followup,
  SalaryRecord,
  SalaryPayment,
  Expense,
  ActivityLog,
  AppNotification,
  AgencySettings,
} from '../types';

export const INITIAL_SETTINGS: AgencySettings = {
  id: 'stg-01',
  agency_name: 'FINEX WEB',
  phone: '+91 98765 43210',
  email: 'finexxweb@gmail.com',
  website: 'https://finexweb.com',
  address: 'Level 4, Trade Centre, BKC, Mumbai 400051',
  starter_price: 9999,
  starter_maint: 999,
  pro_price: 14999,
  pro_maint: 1499,
  biz_price: 24999,
  biz_maint: 1999,
  hosting_renewal: 999,
  currency: 'INR',
  currency_symbol: '₹',
  created_at: '2026-01-01T00:00:00Z',
};

export const INITIAL_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'tm-01',
    employee_id: 'EMP-01',
    full_name: 'Vikram Mehta',
    phone: '+91 98201 11223',
    email: 'vikram@finexweb.com',
    role: 'OWNER / ADMIN',
    department: 'Executive',
    joining_date: '2025-01-01',
    employment_status: 'ACTIVE',
    salary_type: 'MONTHLY',
    monthly_salary: 85000,
    payment_schedule: '1st of month',
    skills: ['Agency Management', 'Full Stack Architecture', 'Client Closing'],
    created_at: '2025-01-01T09:00:00Z',
  },
  {
    id: 'tm-02',
    employee_id: 'EMP-02',
    full_name: 'Rahul Sharma',
    phone: '+91 98334 22334',
    email: 'rahul@finexweb.com',
    role: 'WEB DEVELOPER',
    department: 'Development',
    joining_date: '2025-03-15',
    employment_status: 'ACTIVE',
    salary_type: 'MONTHLY',
    monthly_salary: 35000,
    payment_schedule: '1st of month',
    skills: ['React', 'Next.js', 'Tailwind CSS', 'TypeScript', 'Node.js'],
    created_at: '2025-03-15T09:00:00Z',
  },
  {
    id: 'tm-03',
    employee_id: 'EMP-03',
    full_name: 'Priya Nair',
    phone: '+91 98711 33445',
    email: 'priya@finexweb.com',
    role: 'UI/UX DESIGNER',
    department: 'Design',
    joining_date: '2025-04-01',
    employment_status: 'ACTIVE',
    salary_type: 'MONTHLY',
    monthly_salary: 32000,
    payment_schedule: '1st of month',
    skills: ['Figma', 'Wireframing', 'Design Systems', 'Mobile-First UI'],
    created_at: '2025-04-01T09:00:00Z',
  },
  {
    id: 'tm-04',
    employee_id: 'EMP-04',
    full_name: 'Amit Patel',
    phone: '+91 98920 44556',
    email: 'amit@finexweb.com',
    role: 'PROJECT MANAGER',
    department: 'Operations',
    joining_date: '2025-05-10',
    employment_status: 'ACTIVE',
    salary_type: 'MONTHLY',
    monthly_salary: 40000,
    payment_schedule: '1st of month',
    skills: ['Sprint Planning', 'Client Relations', 'Quality Assurance', 'Timeline Delivery'],
    created_at: '2025-05-10T09:00:00Z',
  },
  {
    id: 'tm-05',
    employee_id: 'EMP-05',
    full_name: 'Sneha Deshmukh',
    phone: '+91 98450 55667',
    email: 'sneha@finexweb.com',
    role: 'FRONTEND DEVELOPER',
    department: 'Development',
    joining_date: '2025-08-01',
    employment_status: 'ACTIVE',
    salary_type: 'MONTHLY',
    monthly_salary: 28000,
    payment_schedule: '1st of month',
    skills: ['HTML5', 'CSS3', 'React', 'Animation', 'Responsive Layouts'],
    created_at: '2025-08-01T09:00:00Z',
  },
  {
    id: 'tm-06',
    employee_id: 'EMP-06',
    full_name: 'Rohan Verma',
    phone: '+91 98199 66778',
    email: 'rohan@finexweb.com',
    role: 'TESTER',
    department: 'Quality Assurance',
    joining_date: '2025-11-15',
    employment_status: 'ACTIVE',
    salary_type: 'MONTHLY',
    monthly_salary: 24000,
    payment_schedule: '1st of month',
    skills: ['Manual Testing', 'Cross-Browser Verification', 'SEO Audit', 'Speed Optimization'],
    created_at: '2025-11-15T09:00:00Z',
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cl-01',
    client_code: 'CL-101',
    client_name: 'Rajesh Khanna',
    business_name: 'The Royal Treat Fine Dining',
    phone: '+91 98200 45678',
    whatsapp: '+91 98200 45678',
    email: 'contact@royaltreat.in',
    city: 'Mumbai',
    address: '42 Hill Road, Bandra West, Mumbai 400050',
    business_category: 'Restaurant & Hospitality',
    lead_source: 'Google Ads',
    date_joined: '2026-06-15',
    status: 'ACTIVE',
    notes: 'Premium dining restaurant requiring digital menu, table booking, and Google Maps integration.',
    created_at: '2026-06-15T10:00:00Z',
  },
  {
    id: 'cl-02',
    client_code: 'CL-102',
    client_name: 'Dr. Ananya Sen',
    business_name: 'Aura Skin & Dental Care',
    phone: '+91 98310 98765',
    whatsapp: '+91 98310 98765',
    email: 'info@auraclinic.co',
    city: 'Pune',
    address: '102 Koregaon Park Plaza, Pune 411001',
    business_category: 'Healthcare & Wellness',
    lead_source: 'Referral',
    date_joined: '2026-07-01',
    status: 'ACTIVE',
    notes: 'Clinic website with WhatsApp appointment consultation and doctor profile highlights.',
    created_at: '2026-07-01T11:00:00Z',
  },
  {
    id: 'cl-03',
    client_code: 'CL-103',
    client_name: 'Sunil Agarwal',
    business_name: 'Agarwal Logistics & Haulage',
    phone: '+91 98400 12345',
    whatsapp: '+91 98400 12345',
    email: 'admin@agarwallogistics.com',
    city: 'Ahmedabad',
    address: 'GIDC Transport Nagar, Ahmedabad 382445',
    business_category: 'Logistics & Supply Chain',
    lead_source: 'Direct Outreach',
    date_joined: '2026-08-10',
    status: 'ACTIVE',
    notes: 'Enterprise fleet showcase with rate calculator and quotation form.',
    created_at: '2026-08-10T14:30:00Z',
  },
  {
    id: 'cl-04',
    client_code: 'CL-104',
    client_name: 'Meera Iyer',
    business_name: 'Vedic Threads Boutique',
    phone: '+91 98800 67890',
    whatsapp: '+91 98800 67890',
    email: 'hello@vedicthreads.shop',
    city: 'Bengaluru',
    address: '88 Indiranagar 100ft Road, Bengaluru 560038',
    business_category: 'Fashion & E-Commerce',
    lead_source: 'Instagram Inbound',
    date_joined: '2026-08-28',
    status: 'ACTIVE',
    notes: 'Handloom apparel catalogue with Razorpay checkout integration.',
    created_at: '2026-08-28T09:45:00Z',
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'ld-01',
    lead_code: 'LD-201',
    business_name: 'Apex Fitness & CrossFit',
    client_name: 'Karan Singhania',
    phone: '+91 98212 34567',
    whatsapp: '+91 98212 34567',
    email: 'karan@apexfitness.co',
    city: 'Delhi',
    business_category: 'Fitness & Sports',
    lead_source: 'Website Inbound',
    date_added: '2026-09-20',
    status: 'INTERESTED',
    next_followup: '2026-09-25',
    notes: 'Interested in Professional Plan (₹14,999). Needs membership signup and class schedule.',
    created_at: '2026-09-20T10:30:00Z',
    updated_at: '2026-09-23T12:00:00Z',
  },
  {
    id: 'ld-02',
    lead_code: 'LD-202',
    business_name: 'GreenLeaf Organic Cafe',
    client_name: 'Pooja Hegde',
    phone: '+91 98451 90812',
    whatsapp: '+91 98451 90812',
    email: 'greenleafcafe@gmail.com',
    city: 'Bengaluru',
    business_category: 'Restaurant & Hospitality',
    lead_source: 'Instagram',
    date_added: '2026-09-21',
    status: 'CALL PENDING',
    next_followup: '2026-09-24',
    notes: 'Requested call back regarding Starter Plan (₹9,999) with online food menu.',
    created_at: '2026-09-21T15:20:00Z',
    updated_at: '2026-09-21T15:20:00Z',
  },
  {
    id: 'ld-03',
    lead_code: 'LD-203',
    business_name: 'Kothari Jewellers Heritage',
    client_name: 'Virendra Kothari',
    phone: '+91 98290 56789',
    whatsapp: '+91 98290 56789',
    email: 'kotharijewels@yahoo.com',
    city: 'Jaipur',
    business_category: 'Luxury & Jewelry',
    lead_source: 'Referral',
    date_added: '2026-09-18',
    status: 'FOLLOW-UP',
    next_followup: '2026-09-26',
    notes: 'Quotation sent for Business Pro Plan (₹24,999). High-res catalogue and WhatsApp direct ordering.',
    created_at: '2026-09-18T11:00:00Z',
    updated_at: '2026-09-22T16:00:00Z',
  },
  {
    id: 'ld-04',
    lead_code: 'LD-204',
    business_name: 'Horizon Architects & Studio',
    client_name: 'Arjun Nambiar',
    phone: '+91 98470 33221',
    whatsapp: '+91 98470 33221',
    email: 'arjun@horizonstudio.in',
    city: 'Kochi',
    business_category: 'Architecture & Interior',
    lead_source: 'Google Ads',
    date_added: '2026-09-23',
    status: 'NEW LEAD',
    next_followup: '2026-09-24',
    notes: 'Looking for a minimal dark-mode portfolio site to present residential projects.',
    created_at: '2026-09-23T08:45:00Z',
    updated_at: '2026-09-23T08:45:00Z',
  },
];

export const INITIAL_CALLS: Call[] = [
  {
    id: 'cl-call-01',
    lead_id: 'ld-01',
    contact_name: 'Karan Singhania (Apex Fitness)',
    phone: '+91 98212 34567',
    call_date: '2026-09-22',
    call_time: '04:30 PM',
    call_status: 'INTERESTED',
    notes: 'Discussed schedule features. Karan was happy with ₹14,999 budget. Sent requirement form.',
    next_followup: '2026-09-25',
    created_at: '2026-09-22T16:30:00Z',
  },
  {
    id: 'cl-call-02',
    lead_id: 'ld-03',
    contact_name: 'Virendra Kothari (Kothari Jewellers)',
    phone: '+91 98290 56789',
    call_date: '2026-09-21',
    call_time: '11:15 AM',
    call_status: 'CONNECTED',
    notes: 'Walked through demo jewelry portfolio. Requested quote including 1 year hosting and maintenance.',
    next_followup: '2026-09-26',
    created_at: '2026-09-21T11:15:00Z',
  },
];

export const INITIAL_REQUIREMENTS: Requirement[] = [
  {
    id: 'req-01',
    req_code: 'REQ-101',
    business_name: 'Apex Fitness & CrossFit',
    lead_id: 'ld-01',
    client_name: 'Karan Singhania',
    business_type: 'Fitness Gym',
    website_type: 'Business',
    number_of_pages: 5,
    features: ['WhatsApp', 'Contact Form', 'Google Maps', 'Booking', 'Gallery'],
    reference_websites: 'https://equinox.com, https://cult.fit',
    budget: 14999,
    deadline: '2026-10-15',
    special_requirements: 'Trainer bio cards, dynamic timetable grid, and instant WhatsApp booking trigger.',
    notes: 'Client insists on bold red & black contrast theme matching their gym aesthetic.',
    status: 'IN PROGRESS',
    created_at: '2026-09-22T17:00:00Z',
  },
  {
    id: 'req-02',
    req_code: 'REQ-102',
    business_name: 'Vedic Threads Boutique',
    client_id: 'cl-04',
    client_name: 'Meera Iyer',
    business_type: 'Handloom Fashion',
    website_type: 'E-commerce',
    number_of_pages: 8,
    features: ['WhatsApp', 'Contact Form', 'Payment', 'Gallery', 'E-commerce'],
    reference_websites: 'https://fabindia.com, https://nicobar.com',
    budget: 24999,
    deadline: '2026-10-05',
    special_requirements: 'Fabric detail zoom, filter by saree type and price, Razorpay gateway.',
    notes: 'Photoshoot images delivered via Google Drive.',
    status: 'COMPLETED',
    created_at: '2026-08-29T10:00:00Z',
  },
];

export const INITIAL_QUOTES: Quote[] = [
  {
    id: 'qt-01',
    quote_code: 'QT-501',
    client_id: 'cl-01',
    client_name: 'Rajesh Khanna',
    business_name: 'The Royal Treat Fine Dining',
    selected_plan: 'PROFESSIONAL',
    development_price: 14999,
    maintenance_price: 1499,
    hosting: '1 Year Included (₹999/yr renewal)',
    domain: 'Separate (royaltreat.in booked by client)',
    discount: 0,
    final_price: 14999,
    quote_date: '2026-06-16',
    status: 'ACCEPTED',
    notes: 'Accepted via WhatsApp message. Advanced 50% paid on signup.',
    created_at: '2026-06-16T12:00:00Z',
  },
  {
    id: 'qt-02',
    quote_code: 'QT-502',
    client_id: 'cl-04',
    client_name: 'Meera Iyer',
    business_name: 'Vedic Threads Boutique',
    selected_plan: 'BUSINESS PRO',
    development_price: 24999,
    maintenance_price: 1999,
    hosting: '1 Year Included (₹999/yr renewal)',
    domain: 'Included (.shop)',
    discount: 1000,
    final_price: 23999,
    quote_date: '2026-08-30',
    status: 'ACCEPTED',
    notes: 'Festive season discount applied. Full deployment scheduled for October.',
    created_at: '2026-08-30T14:00:00Z',
  },
  {
    id: 'qt-03',
    quote_code: 'QT-503',
    client_name: 'Virendra Kothari',
    business_name: 'Kothari Jewellers Heritage',
    selected_plan: 'BUSINESS PRO',
    development_price: 24999,
    maintenance_price: 1999,
    hosting: '1 Year Included',
    domain: 'Separate',
    discount: 0,
    final_price: 24999,
    quote_date: '2026-09-22',
    status: 'SENT',
    notes: 'Sent formal PDF quote to client email. Awaiting review with family directors.',
    created_at: '2026-09-22T18:00:00Z',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj-01',
    project_code: 'PRJ-301',
    client_id: 'cl-01',
    client_name: 'Rajesh Khanna',
    business_name: 'The Royal Treat Fine Dining',
    plan: 'PROFESSIONAL',
    project_price: 14999,
    maintenance_fee: 1499,
    start_date: '2026-06-18',
    deadline: '2026-07-20',
    status: 'MAINTENANCE',
    website_url: 'https://royaltreat.in',
    github_url: 'https://github.com/finexweb/royal-treat',
    domain: 'royaltreat.in',
    hosting: 'FINEX Cloud Server #1',
    notes: 'Project successfully delivered. Under active monthly maintenance plan.',
    progress: 100,
    created_at: '2026-06-18T10:00:00Z',
  },
  {
    id: 'prj-02',
    project_code: 'PRJ-302',
    client_id: 'cl-02',
    client_name: 'Dr. Ananya Sen',
    business_name: 'Aura Skin & Dental Care',
    plan: 'STARTER',
    project_price: 9999,
    maintenance_fee: 999,
    start_date: '2026-07-05',
    deadline: '2026-08-05',
    status: 'MAINTENANCE',
    website_url: 'https://auraclinic.co',
    github_url: 'https://github.com/finexweb/aura-clinic',
    domain: 'auraclinic.co',
    hosting: 'FINEX Cloud Server #1',
    notes: 'Clinic website running smoothly. Doctors reported 25+ patient enquiries in August.',
    progress: 100,
    created_at: '2026-07-05T09:00:00Z',
  },
  {
    id: 'prj-03',
    project_code: 'PRJ-303',
    client_id: 'cl-03',
    client_name: 'Sunil Agarwal',
    business_name: 'Agarwal Logistics & Haulage',
    plan: 'PROFESSIONAL',
    project_price: 14999,
    maintenance_fee: 1499,
    start_date: '2026-08-15',
    deadline: '2026-09-30',
    status: 'DEVELOPMENT',
    website_url: 'https://staging.agarwallogistics.finexweb.com',
    github_url: 'https://github.com/finexweb/agarwal-logistics',
    domain: 'agarwallogistics.com',
    hosting: 'FINEX Staging Server #2',
    notes: 'Responsive UI completed. Building the fleet route quotation calculator.',
    progress: 65,
    created_at: '2026-08-15T11:00:00Z',
  },
  {
    id: 'prj-04',
    project_code: 'PRJ-304',
    client_id: 'cl-04',
    client_name: 'Meera Iyer',
    business_name: 'Vedic Threads Boutique',
    plan: 'BUSINESS PRO',
    project_price: 23999,
    maintenance_fee: 1999,
    start_date: '2026-09-02',
    deadline: '2026-10-10',
    status: 'DESIGN',
    website_url: 'https://vedicthreads-preview.finexdemo.com',
    github_url: 'https://github.com/finexweb/vedic-threads',
    domain: 'vedicthreads.shop',
    hosting: 'FINEX Staging Server #1',
    notes: 'Figma mockups approved. Setting up catalog taxonomy and typography pairing.',
    progress: 35,
    created_at: '2026-09-02T13:00:00Z',
  },
];

export const INITIAL_PROJECT_MEMBERS: ProjectMember[] = [
  {
    id: 'pm-01',
    project_id: 'prj-03',
    team_member_id: 'tm-04',
    member_name: 'Amit Patel',
    role: 'Project Manager',
    assigned_date: '2026-08-15',
    work_status: 'ACTIVE',
  },
  {
    id: 'pm-02',
    project_id: 'prj-03',
    team_member_id: 'tm-02',
    member_name: 'Rahul Sharma',
    role: 'Web Developer',
    assigned_date: '2026-08-15',
    work_status: 'ACTIVE',
  },
  {
    id: 'pm-03',
    project_id: 'prj-03',
    team_member_id: 'tm-06',
    member_name: 'Rohan Verma',
    role: 'Tester',
    assigned_date: '2026-09-20',
    work_status: 'ACTIVE',
  },
  {
    id: 'pm-04',
    project_id: 'prj-04',
    team_member_id: 'tm-03',
    member_name: 'Priya Nair',
    role: 'UI/UX Designer',
    assigned_date: '2026-09-02',
    work_status: 'ACTIVE',
  },
  {
    id: 'pm-05',
    project_id: 'prj-04',
    team_member_id: 'tm-05',
    member_name: 'Sneha Deshmukh',
    role: 'Frontend Developer',
    assigned_date: '2026-09-05',
    work_status: 'ACTIVE',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk-01',
    task_code: 'TSK-401',
    project_id: 'prj-03',
    project_name: 'Agarwal Logistics & Haulage',
    task_name: 'Homepage Development',
    description: 'Implement dark modern hero, counters, service matrix, and responsive navbar.',
    assigned_to: 'tm-02',
    assigned_name: 'Rahul Sharma',
    priority: 'HIGH',
    due_date: '2026-09-26',
    status: 'IN PROGRESS',
    created_date: '2026-09-15',
    notes: 'Verify mobile collapse and touch friendliness.',
  },
  {
    id: 'tsk-02',
    task_code: 'TSK-402',
    project_id: 'prj-03',
    project_name: 'Agarwal Logistics & Haulage',
    task_name: 'Route Calculator Form',
    description: 'Calculate instant estimate based on distance in km and container weight.',
    assigned_to: 'tm-02',
    assigned_name: 'Rahul Sharma',
    priority: 'URGENT',
    due_date: '2026-09-28',
    status: 'IN PROGRESS',
    created_date: '2026-09-16',
    notes: 'Connect to WhatsApp trigger for instant quotation forwarding.',
  },
  {
    id: 'tsk-03',
    task_code: 'TSK-403',
    project_id: 'prj-03',
    project_name: 'Agarwal Logistics & Haulage',
    task_name: 'Cross Browser Testing',
    description: 'Verify rendering on Safari iOS, Chrome Android, and Firefox.',
    assigned_to: 'tm-06',
    assigned_name: 'Rohan Verma',
    priority: 'MEDIUM',
    due_date: '2026-09-29',
    status: 'TODO',
    created_date: '2026-09-18',
  },
  {
    id: 'tsk-04',
    task_code: 'TSK-404',
    project_id: 'prj-04',
    project_name: 'Vedic Threads Boutique',
    task_name: 'Catalogue UI Design in Figma',
    description: 'Product listing grid, filter sidebar, mobile drawer, and product details view.',
    assigned_to: 'tm-03',
    assigned_name: 'Priya Nair',
    priority: 'HIGH',
    due_date: '2026-09-25',
    status: 'IN PROGRESS',
    created_date: '2026-09-05',
    notes: 'Client Meera reviewed wireframes and approved the minimalist luxury palette.',
  },
  {
    id: 'tsk-05',
    task_code: 'TSK-405',
    project_id: 'prj-04',
    project_name: 'Vedic Threads Boutique',
    task_name: 'Razorpay Gateway Setup',
    description: 'Integrate UPI, Credit Cards, and Netbanking with webhook payment verification.',
    assigned_to: 'tm-05',
    assigned_name: 'Sneha Deshmukh',
    priority: 'MEDIUM',
    due_date: '2026-10-02',
    status: 'TODO',
    created_date: '2026-09-10',
  },
  {
    id: 'tsk-06',
    task_code: 'TSK-406',
    project_id: 'prj-01',
    project_name: 'The Royal Treat Fine Dining',
    task_name: 'Deployment & Final Signoff',
    description: 'Launch production domain and configure Cloudflare SSL.',
    assigned_to: 'tm-02',
    assigned_name: 'Rahul Sharma',
    priority: 'HIGH',
    due_date: '2026-07-18',
    status: 'COMPLETED',
    created_date: '2026-07-10',
    completed_date: '2026-07-17',
    notes: 'Successfully deployed. Client gave 5-star testimonial.',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-01',
    payment_code: 'PAY-701',
    client_id: 'cl-01',
    client_name: 'Rajesh Khanna',
    project_id: 'prj-01',
    project_name: 'The Royal Treat Fine Dining',
    quote_id: 'qt-01',
    total_amount: 14999,
    amount_received: 14999,
    remaining: 0,
    payment_date: '2026-07-20',
    due_date: '2026-07-20',
    payment_method: 'BANK TRANSFER',
    status: 'PAID',
    notes: 'Final settlement cleared via NEFT.',
    created_at: '2026-07-20T16:00:00Z',
  },
  {
    id: 'pay-02',
    payment_code: 'PAY-702',
    client_id: 'cl-02',
    client_name: 'Dr. Ananya Sen',
    project_id: 'prj-02',
    project_name: 'Aura Skin & Dental Care',
    total_amount: 9999,
    amount_received: 9999,
    remaining: 0,
    payment_date: '2026-08-05',
    due_date: '2026-08-05',
    payment_method: 'UPI',
    status: 'PAID',
    notes: 'Paid via GPay UPI business QR.',
    created_at: '2026-08-05T14:30:00Z',
  },
  {
    id: 'pay-03',
    payment_code: 'PAY-703',
    client_id: 'cl-03',
    client_name: 'Sunil Agarwal',
    project_id: 'prj-03',
    project_name: 'Agarwal Logistics & Haulage',
    total_amount: 14999,
    amount_received: 7500,
    remaining: 7499,
    payment_date: '2026-08-15',
    due_date: '2026-09-30',
    payment_method: 'BANK TRANSFER',
    status: 'PARTIAL',
    notes: '50% advance received. Balance ₹7,499 payable upon staging approval.',
    created_at: '2026-08-15T12:00:00Z',
  },
  {
    id: 'pay-04',
    payment_code: 'PAY-704',
    client_id: 'cl-04',
    client_name: 'Meera Iyer',
    project_id: 'prj-04',
    project_name: 'Vedic Threads Boutique',
    quote_id: 'qt-02',
    total_amount: 23999,
    amount_received: 12000,
    remaining: 11999,
    payment_date: '2026-09-02',
    due_date: '2026-10-10',
    payment_method: 'BANK TRANSFER',
    status: 'PARTIAL',
    notes: 'Advance 50% paid. Balance due upon deployment.',
    created_at: '2026-09-02T15:30:00Z',
  },
];

export const INITIAL_MAINTENANCE: Maintenance[] = [
  {
    id: 'mnt-01',
    maintenance_code: 'MNT-801',
    client_id: 'cl-01',
    client_name: 'Rajesh Khanna',
    project_id: 'prj-01',
    project_name: 'The Royal Treat Fine Dining',
    plan: 'PROFESSIONAL',
    monthly_fee: 1499,
    start_date: '2026-07-24',
    next_due_date: '2026-09-24', // Due today
    last_payment_date: '2026-08-24',
    payment_status: 'PAYMENT DUE',
    status: 'ACTIVE',
    notes: 'Monthly billing cycle. Includes 2 menu updates and monthly security backup.',
    created_at: '2026-07-24T10:00:00Z',
  },
  {
    id: 'mnt-02',
    maintenance_code: 'MNT-802',
    client_id: 'cl-02',
    client_name: 'Dr. Ananya Sen',
    project_id: 'prj-02',
    project_name: 'Aura Skin & Dental Care',
    plan: 'STARTER',
    monthly_fee: 999,
    start_date: '2026-08-05',
    next_due_date: '2026-10-05',
    last_payment_date: '2026-09-05',
    payment_status: 'ACTIVE',
    status: 'ACTIVE',
    notes: 'Paid on 5th September. Next billing 5th October.',
    created_at: '2026-08-05T10:00:00Z',
  },
];

export const INITIAL_HOSTING: HostingRecord[] = [
  {
    id: 'hst-01',
    client_id: 'cl-01',
    client_name: 'Rajesh Khanna',
    project_id: 'prj-01',
    domain_name: 'royaltreat.in',
    provider: 'FINEX Cloud Server #1',
    start_date: '2026-07-20',
    expiry_date: '2027-07-20',
    renewal_amount: 999,
    status: 'ACTIVE',
    notes: 'Year 1 included in quote. Renewal due July 2027.',
    created_at: '2026-07-20T10:00:00Z',
  },
  {
    id: 'hst-02',
    client_id: 'cl-02',
    client_name: 'Dr. Ananya Sen',
    project_id: 'prj-02',
    domain_name: 'auraclinic.co',
    provider: 'FINEX Cloud Server #1',
    start_date: '2026-08-05',
    expiry_date: '2027-08-05',
    renewal_amount: 999,
    status: 'ACTIVE',
    notes: 'Includes SSL certificate and weekly automated snapshot.',
    created_at: '2026-08-05T10:00:00Z',
  },
];

export const INITIAL_DOMAINS: DomainRecord[] = [
  {
    id: 'dom-01',
    domain_name: 'royaltreat.in',
    client_id: 'cl-01',
    client_name: 'Rajesh Khanna',
    project_id: 'prj-01',
    provider: 'GoDaddy India',
    registration_date: '2026-07-15',
    expiry_date: '2027-07-15',
    renewal_amount: 899,
    status: 'ACTIVE',
    notes: 'DNS managed via Cloudflare.',
    created_at: '2026-07-15T10:00:00Z',
  },
  {
    id: 'dom-02',
    domain_name: 'auraclinic.co',
    client_id: 'cl-02',
    client_name: 'Dr. Ananya Sen',
    project_id: 'prj-02',
    provider: 'Namecheap',
    registration_date: '2026-07-28',
    expiry_date: '2027-07-28',
    renewal_amount: 1299,
    status: 'ACTIVE',
    notes: 'Domain registered for 1 year.',
    created_at: '2026-07-28T10:00:00Z',
  },
];

export const INITIAL_FOLLOWUPS: Followup[] = [
  {
    id: 'fol-01',
    lead_id: 'ld-02',
    client_name: 'Pooja Hegde (GreenLeaf Cafe)',
    phone: '+91 98451 90812',
    reason: 'Call pending regarding Starter Plan ₹9,999 proposal',
    date: '2026-09-24', // Today
    time: '02:00 PM',
    notes: 'Explain 1-year hosting included and 7-day delivery timeline.',
    status: 'PENDING',
    created_at: '2026-09-21T15:25:00Z',
  },
  {
    id: 'fol-02',
    lead_id: 'ld-01',
    client_name: 'Karan Singhania (Apex Fitness)',
    phone: '+91 98212 34567',
    reason: 'Check status of requirement sheet and confirm advance',
    date: '2026-09-25',
    time: '11:00 AM',
    notes: 'Karan requested call back before the weekend to initiate development.',
    status: 'PENDING',
    created_at: '2026-09-22T16:35:00Z',
  },
  {
    id: 'fol-03',
    client_id: 'cl-01',
    client_name: 'Rajesh Khanna (The Royal Treat)',
    phone: '+91 98200 45678',
    reason: 'Maintenance invoice due today ₹1,499',
    date: '2026-09-24', // Today
    time: '04:00 PM',
    notes: 'Send friendly payment link on WhatsApp.',
    status: 'PENDING',
    created_at: '2026-09-24T06:00:00Z',
  },
];

export const INITIAL_SALARY_RECORDS: SalaryRecord[] = [
  {
    id: 'sal-01',
    employee_id: 'tm-02',
    employee_name: 'Rahul Sharma',
    role: 'WEB DEVELOPER',
    month: 'September',
    year: 2026,
    salary_amount: 35000,
    bonus: 2000,
    deduction: 500,
    advance: 0,
    final_salary: 36500, // 35000 + 2000 - 500
    amount_paid: 20000,
    amount_pending: 16500, // 36500 - 20000
    payment_date: '2026-09-10',
    payment_method: 'BANK TRANSFER',
    payment_status: 'PARTIALLY PAID',
    notes: '₹20,000 mid-month disbursement cleared. Balance ₹16,500 pending.',
    created_at: '2026-09-01T09:00:00Z',
  },
  {
    id: 'sal-02',
    employee_id: 'tm-03',
    employee_name: 'Priya Nair',
    role: 'UI/UX DESIGNER',
    month: 'September',
    year: 2026,
    salary_amount: 32000,
    bonus: 1000,
    deduction: 0,
    advance: 0,
    final_salary: 33000,
    amount_paid: 33000,
    amount_pending: 0,
    payment_date: '2026-09-05',
    payment_method: 'BANK TRANSFER',
    payment_status: 'PAID',
    notes: 'September salary fully disbursed.',
    created_at: '2026-09-01T09:00:00Z',
  },
  {
    id: 'sal-03',
    employee_id: 'tm-04',
    employee_name: 'Amit Patel',
    role: 'PROJECT MANAGER',
    month: 'September',
    year: 2026,
    salary_amount: 40000,
    bonus: 0,
    deduction: 0,
    advance: 5000,
    final_salary: 35000, // 40000 - 5000 advance
    amount_paid: 0,
    amount_pending: 35000,
    payment_status: 'PENDING',
    notes: 'Advance ₹5,000 taken in August adjusted. Full pending.',
    created_at: '2026-09-01T09:00:00Z',
  },
  {
    id: 'sal-04',
    employee_id: 'tm-05',
    employee_name: 'Sneha Deshmukh',
    role: 'FRONTEND DEVELOPER',
    month: 'September',
    year: 2026,
    salary_amount: 28000,
    bonus: 0,
    deduction: 0,
    advance: 0,
    final_salary: 28000,
    amount_paid: 28000,
    amount_pending: 0,
    payment_date: '2026-09-05',
    payment_method: 'UPI',
    payment_status: 'PAID',
    notes: 'September salary paid via UPI.',
    created_at: '2026-09-01T09:00:00Z',
  },
  {
    id: 'sal-05',
    employee_id: 'tm-06',
    employee_name: 'Rohan Verma',
    role: 'TESTER',
    month: 'September',
    year: 2026,
    salary_amount: 24000,
    bonus: 0,
    deduction: 0,
    advance: 0,
    final_salary: 24000,
    amount_paid: 0,
    amount_pending: 24000,
    payment_status: 'OVERDUE',
    notes: 'Scheduled for 15th September. Disburse immediately.',
    created_at: '2026-09-01T09:00:00Z',
  },
];

export const INITIAL_SALARY_PAYMENTS: SalaryPayment[] = [
  {
    id: 'spay-01',
    salary_record_id: 'sal-01',
    employee_id: 'tm-02',
    employee_name: 'Rahul Sharma',
    amount_paid: 20000,
    payment_date: '2026-09-10',
    payment_method: 'BANK TRANSFER',
    reference_id: 'HDFC-NEFT-992182',
    notes: 'Partial salary payment',
    created_at: '2026-09-10T11:00:00Z',
  },
  {
    id: 'spay-02',
    salary_record_id: 'sal-02',
    employee_id: 'tm-03',
    employee_name: 'Priya Nair',
    amount_paid: 33000,
    payment_date: '2026-09-05',
    payment_method: 'BANK TRANSFER',
    reference_id: 'HDFC-NEFT-991044',
    notes: 'Full salary payment',
    created_at: '2026-09-05T11:00:00Z',
  },
  {
    id: 'spay-03',
    salary_record_id: 'sal-04',
    employee_id: 'tm-05',
    employee_name: 'Sneha Deshmukh',
    amount_paid: 28000,
    payment_date: '2026-09-05',
    payment_method: 'UPI',
    reference_id: 'UPI-99482811',
    notes: 'Full salary payment',
    created_at: '2026-09-05T11:30:00Z',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-01',
    expense_code: 'EXP-901',
    date: '2026-09-01',
    category: 'Software',
    description: 'Figma Organization & Adobe Creative Cloud Subscriptions',
    amount: 5400,
    payment_method: 'BANK TRANSFER',
    vendor: 'Adobe & Figma Inc',
    notes: 'Monthly design software licensing.',
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'exp-02',
    expense_code: 'EXP-902',
    date: '2026-09-03',
    category: 'Hosting',
    description: 'Cloud VPS Cluster Dedicated Server Hosting (Hostinger / Hetzner)',
    amount: 7800,
    payment_method: 'BANK TRANSFER',
    vendor: 'Hostinger Cloud Services',
    notes: 'Agency primary production server hosting all client staging & live sites.',
    created_at: '2026-09-03T11:00:00Z',
  },
  {
    id: 'exp-03',
    expense_code: 'EXP-903',
    date: '2026-09-05',
    category: 'Internet',
    description: 'Airtel High-Speed Fiber 1Gbps Office Connection',
    amount: 2499,
    payment_method: 'UPI',
    vendor: 'Airtel Broadband',
    notes: 'Office connectivity.',
    created_at: '2026-09-05T12:00:00Z',
  },
  {
    id: 'exp-04',
    expense_code: 'EXP-904',
    date: '2026-09-12',
    category: 'Advertising',
    description: 'Meta Ads & Google Local Campaign for Website Leads',
    amount: 15000,
    payment_method: 'BANK TRANSFER',
    vendor: 'Meta Platforms & Google Ads',
    notes: 'Generated 14 qualified inbound agency leads in September.',
    created_at: '2026-09-12T14:00:00Z',
  },
  {
    id: 'exp-05',
    expense_code: 'EXP-905',
    date: '2026-09-18',
    category: 'Office',
    description: 'Office Pantry, Tea/Coffee & Stationery Supplies',
    amount: 3200,
    payment_method: 'CASH',
    vendor: 'Metro Supermarket',
    notes: 'Team supplies.',
    created_at: '2026-09-18T16:00:00Z',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-01',
    date: '2026-09-24',
    time: '06:15 AM',
    admin_name: 'FINEX Admin',
    action: 'Maintenance Payment Due',
    related_record: 'MNT-801 (The Royal Treat)',
    description: 'Monthly maintenance payment due date reached for The Royal Treat Fine Dining (₹1,499).',
    created_at: '2026-09-24T06:15:00Z',
  },
  {
    id: 'act-02',
    date: '2026-09-23',
    time: '08:45 AM',
    admin_name: 'FINEX Admin',
    action: 'Lead Created',
    related_record: 'LD-204 (Horizon Architects)',
    description: 'New inbound lead added from Google Ads for luxury architectural portfolio.',
    created_at: '2026-09-23T08:45:00Z',
  },
  {
    id: 'act-03',
    date: '2026-09-22',
    time: '06:00 PM',
    admin_name: 'FINEX Admin',
    action: 'Quote Sent',
    related_record: 'QT-503 (Kothari Jewellers)',
    description: 'Business Pro quotation sent to Virendra Kothari for ₹24,999.',
    created_at: '2026-09-22T18:00:00Z',
  },
  {
    id: 'act-04',
    date: '2026-09-20',
    time: '03:30 PM',
    admin_name: 'FINEX Admin',
    action: 'Task Assigned',
    related_record: 'TSK-403 (Cross Browser Testing)',
    description: 'Assigned browser testing for Agarwal Logistics project to Rohan Verma.',
    created_at: '2026-09-20T15:30:00Z',
  },
  {
    id: 'act-05',
    date: '2026-09-10',
    time: '11:00 AM',
    admin_name: 'FINEX Admin',
    action: 'Salary Paid',
    related_record: 'EMP-02 (Rahul Sharma)',
    description: 'Recorded partial salary payment of ₹20,000 for September 2026.',
    created_at: '2026-09-10T11:00:00Z',
  },
];
